### ISSUE TITLE
Some updates

### ISSUE THREAD

**Issue by nortxort** [TechWhizZ199/roombot#1]
You might wanna change disconnect and reconnect to:

    def disconnect(self):
        """ Closes the RTMP connection with the remote server. """
        if self.is_connected:
            try:
                self.is_connected = False
                self.is_client_mod = False
                self.uptime = 0
                self.connection.socket.shutdown(socket.SHUT_RDWR)
                self.connection.socket.close()   
            except Exception as e:
                if DEBUG:
                    print(e.message)

    def reconnect(self):
        """ Reconnect to a room with the connection parameters already set. """
        self.is_reconnected = True
        consol_write(CHAT_ROOM_EVENT_COLOR + '============ RECONNECTING IN 5 SECONDS ============')
        self.disconnect()
        self.request_session = requests.session()
        time.sleep(5)
        if self.account and self.password:
            self.prepare_connect()
        else:
            self.connect()

**Comment by TechWhizZ199** [comment]
Thanks nortxort for your help. I'll make the changes, this project is open to you anytime.
